<?php

namespace ContainerNIqpz68;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MpNKTxyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.MpNKTxy' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.MpNKTxy'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'offre' => ['privates', '.errored..service_locator.MpNKTxy.App\\Entity\\Offres', NULL, 'Cannot autowire service ".service_locator.MpNKTxy": it needs an instance of "App\\Entity\\Offres" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'offre' => 'App\\Entity\\Offres',
        ]);
    }
}
