<?php

namespace ContainerNIqpz68;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMockPaymentControllerpayService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9_8CXPB.App\Controller\Admin\MockPaymentController::pay()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9_8CXPB.App\\Controller\\Admin\\MockPaymentController::pay()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'commande' => ['privates', '.errored..service_locator.9_8CXPB.App\\Entity\\Commandes', NULL, 'Cannot autowire service ".service_locator.9_8CXPB": it needs an instance of "App\\Entity\\Commandes" but this type has been excluded because it\'s a Doctrine entity.'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'commande' => 'App\\Entity\\Commandes',
            'em' => '?',
        ]))->withContext('App\\Controller\\Admin\\MockPaymentController::pay()', $container);
    }
}
