<?php

namespace ContainerNIqpz68;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOffresControllerfilterByCategorieService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2raGOtX.App\Controller\Admin\OffresController::filterByCategorie()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2raGOtX.App\\Controller\\Admin\\OffresController::filterByCategorie()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'offresRepo' => ['privates', 'App\\Repository\\OffresRepository', 'getOffresRepositoryService', true],
            'categoriesOffresRepo' => ['privates', 'App\\Repository\\CategoriesOffresRepository', 'getCategoriesOffresRepositoryService', true],
            'sportRepo' => ['privates', 'App\\Repository\\SportsRepository', 'getSportsRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
        ], [
            'offresRepo' => 'App\\Repository\\OffresRepository',
            'categoriesOffresRepo' => 'App\\Repository\\CategoriesOffresRepository',
            'sportRepo' => 'App\\Repository\\SportsRepository',
            'paginator' => '?',
        ]))->withContext('App\\Controller\\Admin\\OffresController::filterByCategorie()', $container);
    }
}
