<?php

namespace ContainerNIqpz68;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOffresControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2Kdn.t4.App\Controller\Admin\OffresController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2Kdn.t4.App\\Controller\\Admin\\OffresController::edit()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'offresRepo' => ['privates', 'App\\Repository\\OffresRepository', 'getOffresRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
        ], [
            'offresRepo' => 'App\\Repository\\OffresRepository',
            'em' => '?',
            'slugger' => '?',
        ]))->withContext('App\\Controller\\Admin\\OffresController::edit()', $container);
    }
}
