<?php

namespace ContainerNIqpz68;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSportsControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.F4iHO.j.App\Controller\Admin\SportsController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.F4iHO.j.App\\Controller\\Admin\\SportsController::edit()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'sportsRepo' => ['privates', 'App\\Repository\\SportsRepository', 'getSportsRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
        ], [
            'sportsRepo' => 'App\\Repository\\SportsRepository',
            'em' => '?',
            'slugger' => '?',
        ]))->withContext('App\\Controller\\Admin\\SportsController::edit()', $container);
    }
}
