<?php

namespace ContainerNIqpz68;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTwoFactorControllersetupService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4l6F4PT.App\Controller\TwoFactorController::setup()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4l6F4PT.App\\Controller\\TwoFactorController::setup()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'totpService' => ['privates', 'App\\Service\\TOTPService', 'getTOTPServiceService', true],
        ], [
            'totpService' => 'App\\Service\\TOTPService',
        ]))->withContext('App\\Controller\\TwoFactorController::setup()', $container);
    }
}
