<?php

namespace ContainerNIqpz68;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTwoFactorControllerverifyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.htGrwuj.App\Controller\TwoFactorController::verify()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.htGrwuj.App\\Controller\\TwoFactorController::verify()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'userRepository' => ['privates', 'App\\Repository\\UsersRepository', 'getUsersRepositoryService', true],
            'totpService' => ['privates', 'App\\Service\\TOTPService', 'getTOTPServiceService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'userRepository' => 'App\\Repository\\UsersRepository',
            'totpService' => 'App\\Service\\TOTPService',
            'em' => '?',
        ]))->withContext('App\\Controller\\TwoFactorController::verify()', $container);
    }
}
