<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container43y5uF3\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container43y5uF3/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container43y5uF3.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container43y5uF3\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container43y5uF3\App_KernelDevDebugContainer([
    'container.build_hash' => '43y5uF3',
    'container.build_id' => 'fa1b0d2d',
    'container.build_time' => 1758637056,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container43y5uF3');
