<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOjxRhbM\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOjxRhbM/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOjxRhbM.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOjxRhbM\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOjxRhbM\App_KernelDevDebugContainer([
    'container.build_hash' => 'OjxRhbM',
    'container.build_id' => 'e602434a',
    'container.build_time' => 1758502724,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOjxRhbM');
