<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Commandes extends \App\Entity\Commandes implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'created_at' => [parent::class, 'created_at', null, 16],
        "\0".parent::class."\0".'dateScan' => [parent::class, 'dateScan', null, 16],
        "\0".parent::class."\0".'detailsCommandes' => [parent::class, 'detailsCommandes', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'payee_le' => [parent::class, 'payee_le', null, 16],
        "\0".parent::class."\0".'qrToken' => [parent::class, 'qrToken', null, 16],
        "\0".parent::class."\0".'reference' => [parent::class, 'reference', null, 16],
        "\0".parent::class."\0".'scannedBy' => [parent::class, 'scannedBy', null, 16],
        "\0".parent::class."\0".'ticket' => [parent::class, 'ticket', null, 16],
        "\0".parent::class."\0".'user' => [parent::class, 'user', null, 16],
        'created_at' => [parent::class, 'created_at', null, 16],
        'dateScan' => [parent::class, 'dateScan', null, 16],
        'detailsCommandes' => [parent::class, 'detailsCommandes', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'payee_le' => [parent::class, 'payee_le', null, 16],
        'qrToken' => [parent::class, 'qrToken', null, 16],
        'reference' => [parent::class, 'reference', null, 16],
        'scannedBy' => [parent::class, 'scannedBy', null, 16],
        'ticket' => [parent::class, 'ticket', null, 16],
        'user' => [parent::class, 'user', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
