<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Offres extends \App\Entity\Offres implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'categorie' => [parent::class, 'categorie', null, 16],
        "\0".parent::class."\0".'code' => [parent::class, 'code', null, 16],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'dateDebut' => [parent::class, 'dateDebut', null, 16],
        "\0".parent::class."\0".'dateFin' => [parent::class, 'dateFin', null, 16],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null, 16],
        "\0".parent::class."\0".'detailsCommandes' => [parent::class, 'detailsCommandes', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'images' => [parent::class, 'images', null, 16],
        "\0".parent::class."\0".'intitule' => [parent::class, 'intitule', null, 16],
        "\0".parent::class."\0".'isLocked' => [parent::class, 'isLocked', null, 16],
        "\0".parent::class."\0".'isPublished' => [parent::class, 'isPublished', null, 16],
        "\0".parent::class."\0".'nbrAdultes' => [parent::class, 'nbrAdultes', null, 16],
        "\0".parent::class."\0".'nbrEnfants' => [parent::class, 'nbrEnfants', null, 16],
        "\0".parent::class."\0".'prix' => [parent::class, 'prix', null, 16],
        "\0".parent::class."\0".'slug' => [parent::class, 'slug', null, 16],
        "\0".parent::class."\0".'sports' => [parent::class, 'sports', null, 16],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null, 16],
        'categorie' => [parent::class, 'categorie', null, 16],
        'code' => [parent::class, 'code', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'dateDebut' => [parent::class, 'dateDebut', null, 16],
        'dateFin' => [parent::class, 'dateFin', null, 16],
        'description' => [parent::class, 'description', null, 16],
        'detailsCommandes' => [parent::class, 'detailsCommandes', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'images' => [parent::class, 'images', null, 16],
        'intitule' => [parent::class, 'intitule', null, 16],
        'isLocked' => [parent::class, 'isLocked', null, 16],
        'isPublished' => [parent::class, 'isPublished', null, 16],
        'nbrAdultes' => [parent::class, 'nbrAdultes', null, 16],
        'nbrEnfants' => [parent::class, 'nbrEnfants', null, 16],
        'prix' => [parent::class, 'prix', null, 16],
        'slug' => [parent::class, 'slug', null, 16],
        'sports' => [parent::class, 'sports', null, 16],
        'updatedAt' => [parent::class, 'updatedAt', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
