<?php

namespace ContainerYLTeshw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRegistrationControllerverifUserService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pdcOAbz.App\Controller\RegistrationController::verifUser()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pdcOAbz.App\\Controller\\RegistrationController::verifUser()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'jwt' => ['privates', 'App\\Service\\JWTService', 'getJWTServiceService', true],
            'usersRepository' => ['privates', 'App\\Repository\\UsersRepository', 'getUsersRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
        ], [
            'jwt' => 'App\\Service\\JWTService',
            'usersRepository' => 'App\\Repository\\UsersRepository',
            'em' => '?',
            'security' => '?',
        ]))->withContext('App\\Controller\\RegistrationController::verifUser()', $container);
    }
}
