<?php

namespace ContainerYLTeshw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurityControllerforgottenPasswordService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.B8RgYjV.App\Controller\SecurityController::forgottenPassword()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.B8RgYjV.App\\Controller\\SecurityController::forgottenPassword()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'usersRepo' => ['privates', 'App\\Repository\\UsersRepository', 'getUsersRepositoryService', true],
            'jwt' => ['privates', 'App\\Service\\JWTService', 'getJWTServiceService', true],
            'urlGenerator' => ['services', 'router', 'getRouterService', false],
            'mailer' => ['privates', 'App\\Service\\SendEmailService', 'getSendEmailServiceService', true],
        ], [
            'usersRepo' => 'App\\Repository\\UsersRepository',
            'jwt' => 'App\\Service\\JWTService',
            'urlGenerator' => '?',
            'mailer' => 'App\\Service\\SendEmailService',
        ]))->withContext('App\\Controller\\SecurityController::forgottenPassword()', $container);
    }
}
