<?php

namespace ContainerYLTeshw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTOTPServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\TOTPService' shared autowired service.
     *
     * @return \App\Service\TOTPService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/TOTPService.php';

        return $container->privates['App\\Service\\TOTPService'] = new \App\Service\TOTPService();
    }
}
