<?php

namespace Container43y5uF3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ASQ66kBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.aSQ66kB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.aSQ66kB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'commandesRepo' => ['privates', 'App\\Repository\\CommandesRepository', 'getCommandesRepositoryService', true],
        ], [
            'commandesRepo' => 'App\\Repository\\CommandesRepository',
        ]);
    }
}
