<?php

namespace Container43y5uF3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOffresService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.MpNKTxy.App\Entity\Offres' shared service.
     *
     * @return \App\Entity\Offres
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.MpNKTxy": it needs an instance of "App\\Entity\\Offres" but this type has been excluded because it\'s a Doctrine entity.');
    }
}
