<?php

namespace Container43y5uF3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOffresControllernewService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zuLlZtR.App\Controller\Admin\OffresController::new()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zuLlZtR.App\\Controller\\Admin\\OffresController::new()'] = ($container->privates['.service_locator.zuLlZtR'] ?? $container->load('get_ServiceLocator_ZuLlZtRService'))->withContext('App\\Controller\\Admin\\OffresController::new()', $container);
    }
}
