<?php

namespace Container43y5uF3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUsersControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.PMSD29P.App\Controller\Admin\UsersController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.PMSD29P.App\\Controller\\Admin\\UsersController::edit()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'usersRepo' => ['privates', 'App\\Repository\\UsersRepository', 'getUsersRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'usersRepo' => 'App\\Repository\\UsersRepository',
            'em' => '?',
        ]))->withContext('App\\Controller\\Admin\\UsersController::edit()', $container);
    }
}
