<?php

namespace ContainerLQnk9l6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommandeScanControllerscanCommandeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..5KpnnQ.App\Controller\Admin\CommandeScanController::scanCommande()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..5KpnnQ.App\\Controller\\Admin\\CommandeScanController::scanCommande()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repo' => ['privates', 'App\\Repository\\CommandesRepository', 'getCommandesRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'security' => ['privates', '.errored..service_locator..5KpnnQ.Symfony\\Bundle\\SecurityBundle\\SecurityBundle', NULL, 'Cannot autowire service ".service_locator..5KpnnQ": it references class "Symfony\\Bundle\\SecurityBundle\\SecurityBundle" but no such service exists.'],
        ], [
            'repo' => 'App\\Repository\\CommandesRepository',
            'em' => '?',
            'security' => 'Symfony\\Bundle\\SecurityBundle\\SecurityBundle',
        ]))->withContext('App\\Controller\\Admin\\CommandeScanController::scanCommande()', $container);
    }
}
