<?php

namespace ContainerLQnk9l6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMockPaymentControllershowTicketService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zUW4aVC.App\Controller\Admin\MockPaymentController::showTicket()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zUW4aVC.App\\Controller\\Admin\\MockPaymentController::showTicket()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'ticketsRepo' => ['privates', 'App\\Repository\\TicketsRepository', 'getTicketsRepositoryService', true],
        ], [
            'ticketsRepo' => 'App\\Repository\\TicketsRepository',
        ]))->withContext('App\\Controller\\Admin\\MockPaymentController::showTicket()', $container);
    }
}
