<?php

namespace ContainerXmRxF6D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurityBundleService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator..5KpnnQ.Symfony\Bundle\SecurityBundle\SecurityBundle' shared service.
     *
     * @return \Symfony\Bundle\SecurityBundle\SecurityBundle
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator..5KpnnQ": it references class "Symfony\\Bundle\\SecurityBundle\\SecurityBundle" but no such service exists.');
    }
}
