<?php

namespace ContainerXmRxF6D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUsersControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.DbNBHcb.App\Controller\Admin\UsersController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.DbNBHcb.App\\Controller\\Admin\\UsersController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'usersRepo' => ['privates', 'App\\Repository\\UsersRepository', 'getUsersRepositoryService', true],
        ], [
            'usersRepo' => 'App\\Repository\\UsersRepository',
        ]))->withContext('App\\Controller\\Admin\\UsersController::index()', $container);
    }
}
