<?php

namespace Container82wDx8O;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOffresControllercatalogueService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ELqoHnT.App\Controller\Admin\OffresController::catalogue()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ELqoHnT.App\\Controller\\Admin\\OffresController::catalogue()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'offresRepo' => ['privates', 'App\\Repository\\OffresRepository', 'getOffresRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
            'categoriesOffresRepo' => ['privates', 'App\\Repository\\CategoriesOffresRepository', 'getCategoriesOffresRepositoryService', true],
            'sportRepo' => ['privates', 'App\\Repository\\SportsRepository', 'getSportsRepositoryService', true],
        ], [
            'offresRepo' => 'App\\Repository\\OffresRepository',
            'paginator' => '?',
            'categoriesOffresRepo' => 'App\\Repository\\CategoriesOffresRepository',
            'sportRepo' => 'App\\Repository\\SportsRepository',
        ]))->withContext('App\\Controller\\Admin\\OffresController::catalogue()', $container);
    }
}
