<?php

namespace Container82wDx8O;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSportsControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6BXpqYw.App\Controller\Admin\SportsController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6BXpqYw.App\\Controller\\Admin\\SportsController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'sportsRepo' => ['privates', 'App\\Repository\\SportsRepository', 'getSportsRepositoryService', true],
        ], [
            'sportsRepo' => 'App\\Repository\\SportsRepository',
        ]))->withContext('App\\Controller\\Admin\\SportsController::index()', $container);
    }
}
