<?php

namespace ContainerOz7atGj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategoriesOffresControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.iTJSlix.App\Controller\Admin\CategoriesOffresController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.iTJSlix.App\\Controller\\Admin\\CategoriesOffresController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'categoriesOffresRepo' => ['privates', 'App\\Repository\\CategoriesOffresRepository', 'getCategoriesOffresRepositoryService', true],
        ], [
            'categoriesOffresRepo' => 'App\\Repository\\CategoriesOffresRepository',
        ]))->withContext('App\\Controller\\Admin\\CategoriesOffresController::index()', $container);
    }
}
