<?php

namespace ContainerOz7atGj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategoriesOffresControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JmFIrX_.App\Controller\Admin\CategoriesOffresController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JmFIrX_.App\\Controller\\Admin\\CategoriesOffresController::edit()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'categoriesOffresRepo' => ['privates', 'App\\Repository\\CategoriesOffresRepository', 'getCategoriesOffresRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
        ], [
            'categoriesOffresRepo' => 'App\\Repository\\CategoriesOffresRepository',
            'em' => '?',
            'slugger' => '?',
        ]))->withContext('App\\Controller\\Admin\\CategoriesOffresController::edit()', $container);
    }
}
