<?php

namespace ContainerOz7atGj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTwoFactorSetupControllersetupService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.g9vD4Q0.App\Controller\TwoFactorSetupController::setup()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.g9vD4Q0.App\\Controller\\TwoFactorSetupController::setup()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'totpService' => ['privates', 'App\\Service\\TOTPService', 'getTOTPServiceService', true],
        ], [
            'em' => '?',
            'totpService' => 'App\\Service\\TOTPService',
        ]))->withContext('App\\Controller\\TwoFactorSetupController::setup()', $container);
    }
}
